### ISSUE TITLE
wheel does not spin on firefox 129

### ISSUE THREAD

**Issue by binslashseo** [halsschmerzen/distrohopper-wheel#1]
a look at the console told me that it apparently blocks the sans-serif font or something linked to it (?)
don't really have an idea of what to do

**Comment by halsschmerzen** [comment]
I checked your problem and I see the issue with the fonts in the console aswell. However, that doesn't explain why your wheel isn't spinning.

You clicked the button and nothing happened right?

**Comment by halsschmerzen** [comment]
> a look at the console told me that it apparently blocks the sans-serif font or something linked to it (?) don't really have an idea of what to do

btw I'm also using firefox 129. Have you tried a different browser? On what platform are you on :)?

**Comment by 00000000000090000000000** [comment]
i'm on windows 11 (don't judge it's what i was browsing reddit from that day) and no i've not tried a different browser. i'll try that and get back to you

**Comment by 00000000000090000000000** [comment]
seems like it was a one time occurence. the wheel spins on firefox (win11) and qutebrowser (debian). great project!
