### ISSUE TITLE
can't scoll down to the spin button

### ISSUE THREAD

**Issue by huybin1234b** [halsschmerzen/distrohopper-wheel#2]
I'm using thorium and seems I can't scroll down to the spin button even though I'm using full screen
Here is my device information *(for some privacy I'm gonna hide something there)*
<img width="838" alt="image" src="https://github.com/user-attachments/assets/ae7cac02-ef23-44bd-82de-984e2b5fe699">
![image](https://github.com/user-attachments/assets/fb64a8f8-844d-44be-8592-60398fa4c81b)

**Comment by halsschmerzen** [comment]
There seems to be an issue with <1080p screens. I'm working on this right now! Thanks for the report :)

**Comment by halsschmerzen** [comment]
> I'm using thorium and seems I can't scroll down to the spin button even though I'm using full screen Here is my device information _(for some privacy I'm gonna hide something there)_ <img alt="image" width="838" src="https://private-user-images.githubusercontent.com/103201882/359431078-ae7cac02-ef23-44bd-82de-984e2b5fe699.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTM1NzksIm5iZiI6MTcyNDE1MzI3OSwicGF0aCI6Ii8xMDMyMDE4ODIvMzU5NDMxMDc4LWFlN2NhYzAyLWVmMjMtNDRiZC04MmRlLTk4NGUyYjVmZTY5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQxMTI3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzY2Y2Y3NWIyN2E5OTBlZmQ3NTFiMzdiZTgzYzZlODUwZDM1ZTlkMjg3ZjY4NGFmNzdhZDMyZDliNDdhZTNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4t6wDNYh3q81-BArUzIg7ToRjp7YjWkXaKVHv5dDQuI"> ![image](https://private-user-images.githubusercontent.com/103201882/359429890-fb64a8f8-844d-44be-8592-60398fa4c81b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTM1NzksIm5iZiI6MTcyNDE1MzI3OSwicGF0aCI6Ii8xMDMyMDE4ODIvMzU5NDI5ODkwLWZiNjRhOGY4LTg0NGQtNDRiZS04NTkyLTYwMzk4ZmE0YzgxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQxMTI3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjM1ZjRjNjQxOGI0NDI5NzJmZWFiYjVjMzllYzgwYWI3ZTUzN2Y1NmY0NzZiODRkYTZiYWVhM2U4ZWVkMmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WSh8iBYbwauF7xYKaugBUDB6GdZVawSL6KNEP3CCC2M)

Should be fixed now :) please let me know if it works for you
